disciplinas = [
    ("Algoritmos e Estrutura de Dados", "Ciência da Computação"),
    ("Cálculo I", "Matemática"),
    ("Física I", "Física"),
    ("Teoria da Computação", "Ciência da Computação"),
    ("Estatística Aplicada", "Estatística"),
    ("Análise de Sistemas", "Sistemas de Informação"),
    ("Programação Orientada a Objetos", "Ciência da Computação"),
    ("Redes de Computadores", "Sistemas de Informação"),
    ("Matemática Discreta", "Matemática"),
    ("Economia", "Economia"),
    ("Linguagens Formais", "Ciência da Computação"),
    ("Administração de Empresas", "Administração"),
    ("Sociologia", "Sociologia"),
    ("Psicologia", "Psicologia"),
    ("Filosofia", "Filosofia"),
    ("Biologia Celular", "Biologia"),
    ("Fisiologia Humana", "Biologia"),
    ("Genética", "Biologia"),
    ("Química Orgânica", "Química"),
    ("Química Analítica", "Química"),
    ("Físico-Química", "Química"),
    ("Geologia", "Geologia"),
    ("Estatística Descriptiva", "Estatística"),
    ("Probabilidade e Estatística", "Estatística"),
    ("Análise de Regressão", "Estatística"),
    ("Teoria da Informação", "Ciência da Computação"),
    ("Sistemas Operacionais", "Sistemas de Informação"),
    ("Banco de Dados", "Sistemas de Informação"),
    ("Engenharia de Software", "Ciência da Computação"),
    ("Análise de Algoritmos", "Ciência da Computação"),
    ("Computação Gráfica", "Ciência da Computação"),
    ("Inteligência Artificial", "Ciência da Computação"),
    ("Redes Neurais", "Ciência da Computação"),
    ("Lógica de Programação", "Ciência da Computação"),
    ("Arquitetura de Computadores", "Ciência da Computação"),
    ("Sistemas de Gerenciamento de Banco de Dados", "Sistemas de Informação"),
    ("Desenvolvimento Web", "Sistemas de Informação"),
    ("Sistemas de Informação Geográfica", "Sistemas de Informação"),
    ("Técnicas de Programação", "Ciência da Computação"),
    ("Gestão de Projetos", "Administração"),
    ("Comunicação e Expressão", "Comunicação Social"),
    ("Psicologia do Desenvolvimento", "Psicologia"),
    ("Psicologia Educacional", "Psicologia"),
    ("Teoria da Aprendizagem", "Psicologia"),
    ("Psicologia Social", "Psicologia"),
    ("Biologia Molecular", "Biologia"),
    ("Genômica", "Biologia"),
    ("Bioquímica", "Química"),
    ("Fisiologia Vegetal", "Biologia"),
    ("Ecologia", "Biologia"),
    ("Zoologia", "Biologia"),
    ("Botânica", "Biologia"),
    ("Geologia Estrutural", "Geologia"),
    ("Geologia Histórica", "Geologia"),
    ("Geografia Humana", "Geografia"),
    ("Geografia Física", "Geografia"),
    ("Estatística Multivariada", "Estatística"),
    ("Modelagem Estatística", "Estatística"),
    ("Teoria da Decisão", "Estatística"),
    ("Análise de Séries Temporais", "Estatística"),
    ("Teoria dos Jogos", "Estatística"),
    ("Análise de Dados", "Estatística"),
    ("Visualização de Dados", "Estatística"),
    ("Mineração de Dados", "Estatística"),
]
