especializacoes = [
    ("Doutor em Inteligência Artificial", "Ciência da Computação"),
    ("Doutor em Redes Neurais", "Ciência da Computação"),
    ("Doutor em Lógica de Programação", "Ciência da Computação"),
    ("Doutor em Arquitetura de Computadores", "Ciência da Computação"),
    ("Doutor em Sistemas de Gerenciamento de Banco de Dados", "Sistemas de Informação"),
    ("Doutor em Desenvolvimento Web", "Sistemas de Informação"),
    ("Doutor em Sistemas de Informação Geográfica", "Sistemas de Informação"),
    ("Doutor em Técnicas de Programação", "Ciência da Computação"),
    ("Doutor em Gestão de Projetos", "Administração"),
    ("Doutor em Comunicação e Expressão", "Comunicação Social"),
    ("Doutor em Psicologia do Desenvolvimento", "Psicologia"),
    ("Doutor em Psicologia Educacional", "Psicologia"),
    ("Doutor em Teoria da Aprendizagem", "Psicologia"),
    ("Doutor em Psicologia Social", "Psicologia"),
    ("Doutor em Biologia Molecular", "Biologia"),
    ("Doutor em Genômica", "Biologia"),
    ("Doutor em Bioquímica", "Química"),
    ("Doutor em Fisiologia Vegetal", "Biologia"),
    ("Doutor em Ecologia", "Biologia"),
    ("Doutor em Zoologia", "Biologia"),
    ("Doutor em Botânica", "Biologia"),
    ("Doutor em Geologia Estrutural", "Geologia"),
    ("Doutor em Geologia Histórica", "Geologia"),
    ("Doutor em Geografia Humana", "Geografia"),
    ("Doutor em Geografia Física", "Geografia"),
    ("Doutor em Estatística Multivariada", "Estatística"),
    ("Doutor em Modelagem Estatística", "Estatística"),
    ("Doutor em Teoria da Decisão", "Estatística"),
    ("Doutor em Análise de Séries Temporais", "Estatística"),
    ("Doutor em Teoria dos Jogos", "Estatística"),
    ("Doutor em Análise de Dados", "Estatística"),
    ("Doutor em Visualização de Dados", "Estatística"),
    ("Doutor em Mineração de Dados", "Estatística"),
]
